sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - docker volume create xqa-message-broker
  - docker pull jameshnsears/xqa-message-broker
  - docker run -d --net="host" --name="xqa-message-broker" -p 127.0.0.1:1099:1099 -p 127.0.0.1:5672:5672 -p 127.0.0.1:8161:8161 -p 127.0.0.1:61616:61616 jameshnsears/xqa-message-broker
  - sleep 10
  - docker logs xqa-message-broker

  - docker pull jameshnsears/xqa-ingest-balancer
  - docker run -d --net="host" --name="xqa-ingest-balancer" jameshnsears/xqa-ingest-balancer

  - docker pull jameshnsears/xqa-shard
  - docker run -d --net="host" --name="xqa-shard-1" jameshnsears/xqa-shard
 
  - sudo apt-get remove cmake
  - sudo apt-get install -y gcc cmake-curses-gui uuid-dev libssl-dev libsasl2-2 libsasl2-dev swig python-dev python3-dev ruby-dev libperl-dev

  - cd ..
  - git clone https://github.com/jameshnsears/xqa-test-data
  - rm -rf xqa-test-data/.git

  - git clone https://github.com/jameshnsears/xqa-ingest
  - cd xqa-ingest
  - pip install -r requirements.txt

script:
  - export PYTHONPATH=/home/travis/build/jameshnsears/xqa-ingest/src:$PYTHONPATH
  - python src/xqa/ingester.py -p ../xqa-test-data > ingester.log

  - sleep 60

  - cat ingester.log
  - docker logs xqa-ingest-balancer

  - docker logs xqa-shard-1 > xqa-shard-1.log
  - cat xqa-shard-1.log

  - grep "\"size\":\"40\"" xqa-shard-1.log
