#
# 1. on ubuntu:bionic containers build xqa images & then publish to docker-hub.
# 2. in vm: use published docker-hub images to test single shard end to end integration.
#

version: 2

jobs:
  "xqa-db":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
      - run: apt install -y git curl

      - run: git clone https://github.com/jameshnsears/xqa-db.git

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          set -x
          cd xqa-db
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-db jameshnsears/xqa-db
          docker push jameshnsears/xqa-db

######################################################

  "xqa-db-amqp":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
      - run: apt remove cmake
      - run: apt install -y git wget python3-pip python3-dev curl
      - run: apt install -y gcc cmake-curses-gui uuid-dev libssl-dev libsasl2-2 libsasl2-dev swig python-dev python3-dev ruby-dev libperl-dev

      - run: git clone https://github.com/jameshnsears/xqa-db-amqp.git

      - restore_cache:
          key: xqa-db-amqp-{{ checksum "xqa-db-amqp/requirements.txt" }}

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            cd xqa-db-amqp
            XQA_PY=3.6.5
            PATH=/usr/local/bin/Python-$XQA_PY/bin:$PATH pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ~/.m2
          key: xqa-db-amqp-{{ checksum "xqa-db-amqp/requirements.txt" }}

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          set -x
          cd xqa-db-amqp
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-db-amqp jameshnsears/xqa-db-amqp
          docker push jameshnsears/xqa-db-amqp

######################################################

  "xqa-ingest":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
      - run: apt install -y openjdk-11-jre git curl maven

      - run: git clone https://github.com/jameshnsears/xqa-ingest.git

      - restore_cache:
          key: xqa-ingest-{{ checksum "xqa-ingest/pom.xml" }}

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            cd xqa-ingest
            mvn package -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: xqa-ingest-{{ checksum "xqa-ingest/pom.xml" }}

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          set -x
          cd xqa-ingest
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-ingest jameshnsears/xqa-ingest
          docker push jameshnsears/xqa-ingest

######################################################

  "xqa-ingest-balancer":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
      - run: apt install -y openjdk-11-jre git curl maven

      - run: git clone https://github.com/jameshnsears/xqa-ingest-balancer.git

      - restore_cache:
          key: xqa-ingest-balancer-{{ checksum "xqa-ingest-balancer/pom.xml" }}

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            cd xqa-ingest-balancer
            mvn package -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: xqa-ingest-balancer-{{ checksum "xqa-ingest-balancer/pom.xml" }}

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          set -x
          cd xqa-ingest-balancer
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-ingest-balancer jameshnsears/xqa-ingest-balancer
          docker push jameshnsears/xqa-ingest-balancer

######################################################

  "xqa-message-broker":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
      - run: apt install -y git curl

      - run: git clone https://github.com/jameshnsears/xqa-message-broker.git

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          set -x
          cd xqa-message-broker
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-message-broker jameshnsears/xqa-message-broker
          docker push jameshnsears/xqa-message-broker

######################################################

  "xqa-query-balancer":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
      - run: apt install -y openjdk-11-jre git curl maven

      - run: git clone https://github.com/jameshnsears/xqa-query-balancer.git

      - restore_cache:
          key: xqa-query-balancer-{{ checksum "xqa-query-balancer/pom.xml" }}

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            cd xqa-query-balancer
            mvn package -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: xqa-query-balancer-{{ checksum "xqa-query-balancer/pom.xml" }}

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          set -x
          cd xqa-query-balancer
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-query-balancer jameshnsears/xqa-query-balancer
          docker push jameshnsears/xqa-query-balancer

######################################################

  "xqa-query-ui":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
        run: apt install -y git wget curl xz-utils sudo

      - run: |
          set -x
          wget --no-check-certificate https://nodejs.org/dist/v8.10.0/node-v8.10.0-linux-x64.tar.xz
          tar xf node-v8.10.0-linux-x64.tar.xz
          rm node-v8.10.0-linux-x64.tar.xz

      - run: git clone https://github.com/jameshnsears/xqa-query-ui.git

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          command: |
            set -x
            cd xqa-query-ui
            export PATH=/root/project/node-v8.10.0-linux-x64/bin:$PATH
            sudo env "PATH=$PATH" npm install

            export PATH=/root/project/xqa-query-ui/node_modules/@angular/cli/bin:$PATH
            ng build --prod --build-optimizer

      - run: |
          set -x
          cd xqa-query-ui
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-query-ui jameshnsears/xqa-query-ui
          docker push jameshnsears/xqa-query-ui

######################################################

  "xqa-shard":
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt update
      - run: apt upgrade -y
      - run: apt remove cmake
      - run: apt install -y git wget python3-pip python3-dev curl
      - run: apt install -y gcc cmake-curses-gui uuid-dev libssl-dev libsasl2-2 libsasl2-dev swig python-dev python3-dev ruby-dev libperl-dev

      - run: git clone https://github.com/jameshnsears/xqa-shard.git

      - restore_cache:
          key: xqa-shard-{{ checksum "xqa-shard/requirements.txt" }}

      - run: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            set -x
            cd xqa-shard
            XQA_PY=3.6.5
            PATH=/usr/local/bin/Python-$XQA_PY/bin:$PATH pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ~/.m2
          key: xqa-shard-{{ checksum "xqa-shard/requirements.txt" }}

      - run:
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          set -x
          cd xqa-shard
          docker-compose build --force-rm

      - run: |
          docker images
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag xqa-shard jameshnsears/xqa-shard
          docker push jameshnsears/xqa-shard

######################################################

  "e2e":
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true 
    steps:
      - run: |
          docker --version
          docker-compose --version

      - run: |
          sudo apt install -y git
          git clone https://github.com/jameshnsears/xqa-documentation
          git clone https://github.com/jameshnsears/xqa-test-data

      - run: |
          set -x
          cd xqa-documentation
          docker-compose -f docker-compose.yml up -d --scale xqa-shard=1
          docker network ls
          docker images
          docker ps -a

      - run: |
          set -x
          docker run -d --net="xqadocumentation_xqa" --name="xqa-ingest" -v /home/circleci/project/xqa-test-data:/xml jameshnsears/xqa-ingest:latest -message_broker_host xqa-message-broker -path /xml

      - run: sleep 180
      - run: docker logs xqa-ingest
      - run: docker logs xqa-ingest-balancer
      - run: docker logs xqa-shard
      - run: docker logs xqa-shard | grep "size=40"

######################################################

workflows:
  version: 2
  commit:
    jobs:
      - "xqa-db"
      - "xqa-db-amqp"
      - "xqa-ingest"
      - "xqa-ingest-balancer"
      - "xqa-message-broker"
      - "xqa-query-balancer"
      - "xqa-query-ui"
      - "xqa-shard"

      - "e2e":
          requires:
            - "xqa-db"
            - "xqa-db-amqp"
            - "xqa-ingest"
            - "xqa-ingest-balancer"
            - "xqa-message-broker"
            - "xqa-query-balancer"
            - "xqa-query-ui"
            - "xqa-shard"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - "xqa-db"
      - "xqa-db-amqp"
      - "xqa-ingest"
      - "xqa-ingest-balancer"
      - "xqa-message-broker"
      - "xqa-query-balancer"
      - "xqa-query-ui"
      - "xqa-shard"

      - "e2e":
          requires:
            - "xqa-db"
            - "xqa-db-amqp"
            - "xqa-ingest"
            - "xqa-ingest-balancer"
            - "xqa-message-broker"
            - "xqa-query-balancer"
            - "xqa-query-ui"
            - "xqa-shard"
