apiVersion: apps/v1
kind: Deployment
metadata:
  name: xqa-shard
  namespace: xqa
  labels:
    app: xqa-shard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xqa-shard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xqa-shard
    spec:
      containers:
        - name: xqa-shard-container
          image: jameshnsears/xqa-shard:latest
          args: ["-message_broker_host", "xqa-message-broker", "-storage_mainmem"]
          resources:
            limits:
              memory: "75Mi"
            requests:
              memory: "75Mi"
          ports:
            - containerPort: 1984
              name: basex