apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xqa-db-pv-claim
  namespace: xqa
  labels:
    app: xqa-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xqa-db
  namespace: xqa
  labels:
    app: xqa-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xqa-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xqa-db
    spec:
      containers:
        - name: xqa-db-container
          image: jameshnsears/xqa-db:latest
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "200Mi"
          ports:
            - containerPort: 5432
              name: xqa-db
          volumeMounts:
            - name: xqa-db-volume
              mountPath: /var/lib/postgresql
      volumes:
        - name: xqa-db-volume
          persistentVolumeClaim:
            claimName: xqa-db-pv-claim